# Generated by Django 3.1.7 on 2023-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20221214_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('customer_dob', models.DateField()),
                ('customer_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
